name: autocoalhmm_minimal
channels:
  - conda-forge
  - anaconda
  - gwforg
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - biopython
  - pandas
  - gwf=1.7.2
  - pytables
  - numpy=1.18.1
