name: autocoalhmm_minimal
channels:
  - conda-forge
  - anaconda
  - gwforg
  - bioconda
  - defaults
dependencies:
  - python=3.7.12
  - biopython=1.79
  - pandas=1.3.1
  - gwf=1.7.2
  - pytables=3.6.1
  - numpy=1.18.1
  - numexpr=2.7.1
